#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode("utf-8")
print("commit-msg: On branch '%s'" % branch)

# Check the commit message if we're on an issue branch
if branch.lower().startswith('feat-'):
    print("commit-msg: Oh hey, it's an issue branch.")
    result = re.match('feat-(.*)', branch, re.IGNORECASE)
    issue_number = result.group(1)
    required_message = "FEAT-%s" % issue_number

    with open(commit_msg_filepath, 'r') as f:
        commit_msg = f.read()
        
    if not commit_msg.lower().startswith(required_message):
        print("commit-msg: ERROR! The commit message must start with '%s'" % required_message)

        out_msg = f"{required_message}: {commit_msg}"
        print('Patching commit msg to: "' + out_msg + '"')
        
        with open(commit_msg_filepath, 'w') as f:
            f.write(out_msg)
